import 'package:shared_preferences/shared_preferences.dart';

// Global variable to store current strings based on selected language
Map<String, String> currentStrings = {};

// Function to load strings based on saved language
Future<void> loadStrings() async {
  final prefs = await SharedPreferences.getInstance();
  final String languageCode = prefs.getString('languageCode') ?? 'en';
  if (languageCode == 'ar') {
    currentStrings = arStrings;
  } else {
    currentStrings = enStrings;
  }
}

// English Strings
const Map<String, String> enStrings = {
  'appTitle': 'HeartSync',
  'appName': 'HeartSync',
  'welcomeMessage': 'Welcome to HeartSync ✨\nLet your heart guide the journey 💖',
  'continueButton': 'Continue',
  'personalInfoTitle': 'Your Personal Info',
  'enterYourName': 'Enter your name',
  'yourName': 'Your Name',
  'enterYourNameHint': 'e.g., John Doe',
  'selectYourGender': 'Select your gender',
  'male': 'Male',
  'female': 'Female',
  'other': 'Other',
  'next': 'Next',
  'yourHeartCode': 'Your Heart Code',
  'heartCodeExplanation': 'This unique code identifies you.',
  'selectYourDOB': 'Select your Date of Birth',
  'selectDate': 'Select Date',
  'yourZodiacSign': 'Your Zodiac Sign',
  'saveAndContinue': 'Save and Continue',
  'aries': 'Aries',
  'taurus': 'Taurus',
  'gemini': 'Gemini',
  'cancer': 'Cancer',
  'leo': 'Leo',
  'virgo': 'Virgo',
  'libra': 'Libra',
  'scorpio': 'Scorpio',
  'sagittarius': 'Sagittarius',
  'capricorn': 'Capricorn',
  'aquarius': 'Aquarius',
  'pisces': 'Pisces',
  'unknown': 'Unknown',
  'pairingTitle': 'Pair with Partner',
  'enterPartnerCode': 'Enter your partner\'s Heart Code',
  'partnerHeartCode': 'Partner\'s Heart Code',
  'pair': 'Pair',
  'orScanQR': 'Or scan QR code',
  'noPartnerYet': 'No partner yet',
  'unknownPartner': 'Unknown Partner',
  'partnerNotFound': 'Partner not found',
  'errorLoadingPartner': 'Error loading partner',
  'heartbeatSent': 'Heartbeat sent!',
  'failedToSendHeartbeat': 'Failed to send heartbeat.',
  'messageSent': 'Message sent!',
  'failedToSendMessage': 'Failed to send message.',
  'settings': 'Settings',
  'language': 'Language',
  'theme': 'App Theme',
  'changePartner': 'Change Partner',
  'logout': 'Log Out',
  'aboutApp': 'About App',
  'languageUpdated': 'Language updated!',
  'themeColorSaved': 'Theme settings saved!',
  'confirmLogout': 'Confirm Logout',
  'areYouSureLogout': 'Are you sure you want to log out?',
  'yes': 'Yes',
  'cancel': 'Cancel',
  'fillAllFields': 'Please fill all fields correctly.',
  'heartCodeExists': 'This Heart Code already exists. Please choose another one.',
  'nameAndGenderRequired': 'Please enter your name and select your gender.',
  'letter': 'Letter',
  'numbers': 'Numbers',
  'back': 'Back',
  'noPartnerToSend': 'No partner to send heartbeat to.',
  'noPartnerToSendMessage': 'No partner to send message to.',
  'messageCannotBeEmpty': 'Message cannot be empty.',
  'swipeToSend': 'Swipe to Send Message',
  'swipeMessage': 'Hello from HeartSync!',
  'menuButtonComingSoon': 'Menu button functionality coming soon!',
  'selectThemeColor': 'Select Theme Color:',
  'confirmChangePartner': 'Confirm Change Partner',
  'areYouSureChangePartner': 'Are you sure you want to change your partner? This will unpair you.',
  'partnerUnpaired': 'Partner un-paired successfully.',
  'copyright': '© 2024 HeartSync. All rights reserved.',
  'appDescription': 'HeartSync is an app designed to help you stay connected with your loved one through simple interactions and reminders.',
  'skipPairing': 'Skip Pairing',
  'confirmPairingTitle': 'Confirm Pairing',
  'confirmPairingMessage': 'Do you want to pair with {partnerName} ({partnerHeartCode})?',
  'accept': 'Accept',
  'decline': 'Decline',
  'pairingRequestSent': 'Pairing request sent. Waiting for partner\'s confirmation.',
  'pairingRequestReceived': 'Pairing request received from {partnerName} ({partnerHeartCode}).',
  'pairingAccepted': 'Pairing successful! You are now connected.',
  'pairingDeclined': 'Pairing declined by partner.',
  'pairingFailed': 'Pairing failed. Please try again.',
  'iMissYouSettingsTitle': 'I Miss You Settings',
  'setReminderTime': 'Set Reminder Time',
  'reminderTime': 'Reminder Time',
  'enableReminders': 'Enable Reminders',
  'reminderMessage': 'It\'s time to check on your partner!',
  'reminderSaved': 'Reminder settings saved!',
  'openAppSettings': 'Open App Settings',
  'appSettingsExplanation': 'To ensure reminders work, please enable notifications for HeartSync in your device settings.',
  'qrScannerTitle': 'Scan QR Code',
  'scanQrCodeInstruction': 'Position the QR code within the frame to scan it.',
  'qrCodeNotFound': 'QR code not found or invalid.',
  'cameraPermissionDenied': 'Camera permission denied. Please enable it in settings.',
  'home': 'Home',
  'iMissYouSettings': 'I Miss You Settings',
  'welcome': 'Welcome',
  'lastInteractionWith': 'Last interaction with',
  'noPartnerMessage': 'It looks like you haven\'t paired with anyone yet. Head to the pairing screen to connect with your partner!',
  'goToPairing': 'Go to Pairing',
  'never': 'Never',
  'secondsAgo': 'seconds ago',
  'minutesAgo': 'minutes ago',
  'hoursAgo': 'hours ago',
  'daysAgo': 'days ago',
  'noPartnerPaired': 'No partner paired yet.',
  'whatsYourName': 'What\'s your name?',
  'yourNameHint': 'Your Name',
  'whatsYourHeartCode': 'What\'s your Heart Code?',
  'whatsYourGender': 'What\'s your gender?',
  'selectBirthdate': 'Your Birth Date',
  'tapToPick': 'Tap to select date',
  'completeBasicInfo': 'Please enter your name, select gender, and enter a valid 5-character heart code (e.g., A1234).',
  'birthdateRequired': 'Please select your birth date.',
  'settingsSaved': 'Settings saved successfully!',
  'errorSavingSettings': 'Error saving information. Please try again.',
  'myHeartCodeLabel': 'Your Heart Code:',
  'tapToCopy': 'Tap to copy',
  'shareMyCode': 'Share My Code',
  'partnerHeartCodeLabel': 'Partner\'s Heart Code:',
  'heartCodeRequired': 'Please enter a valid 5-character heart code (e.g., A1234)',
  'pairNow': 'Pair Now',
  'scanQRCode': 'Scan QR Code',
  'cannotPairWithSelf': 'You cannot pair with your own heart code.',
  'partnerCodeNotFound': 'Partner heart code not found.',
  'partnerAlreadyPaired': 'This partner is already paired with someone else.',
  'pairingSuccess': 'Pairing successful!',
  'pairingError': 'Pairing failed',
  'copiedToClipboard': 'Copied to clipboard!',
  'invalidQrCode': 'Invalid QR code format.',
  'skipPairingTitle': 'Skip Pairing',
  'skipPairingMessage': 'Are you sure you want to skip pairing for now? You can pair later from settings.',
  'settingsTitle': 'Settings',
  'themeColor': 'App Theme Color',
  'logoutConfirmation': 'Are you sure you want to log out?',
  'confirm': 'Confirm',
  'themeUpdated': 'Theme updated',
  'aboutAppTitle': 'About',
};

// Arabic Strings
const Map<String, String> arStrings = {
  'appTitle': 'HeartSync',
  'appName': 'HeartSync',
  'welcomeMessage': 'مرحباً بك في HeartSync ✨\nدع قلبك يقود الرحلة 💖',
  'continueButton': 'متابعة',
  'personalInfoTitle': 'معلوماتك الشخصية',
  'enterYourName': 'أدخل اسمك',
  'yourName': 'اسمك',
  'enterYourNameHint': 'مثال: محمد علي',
  'selectYourGender': 'اختر جنسك',
  'male': 'ذكر',
  'female': 'أنثى',
  'other': 'آخر',
  'next': 'التالي',
  'yourHeartCode': 'رمز القلب الخاص بك',
  'heartCodeExplanation': 'هذا الرمز الفريد يميزك.',
  'selectYourDOB': 'اختر تاريخ ميلادك',
  'selectDate': 'اختر التاريخ',
  'yourZodiacSign': 'برجك الفلكي',
  'saveAndContinue': 'حفظ ومتابعة',
  'aries': 'الحمل',
  'taurus': 'الثور',
  'gemini': 'الجوزاء',
  'cancer': 'السرطان',
  'leo': 'الأسد',
  'virgo': 'العذراء',
  'libra': 'الميزان',
  'scorpio': 'العقرب',
  'sagittarius': 'القوس',
  'capricorn': 'الجدي',
  'aquarius': 'الدلو',
  'pisces': 'الحوت',
  'unknown': 'غير معروف',
  'pairingTitle': 'الربط مع الشريك',
  'enterPartnerCode': 'أدخل رمز قلب شريكك',
  'partnerHeartCode': 'رمز قلب الشريك',
  'pair': 'ربط',
  'orScanQR': 'أو امسح رمز QR',
  'noPartnerYet': 'لا يوجد شريك بعد',
  'unknownPartner': 'شريك غير معروف',
  'partnerNotFound': 'الشريك غير موجود',
  'errorLoadingPartner': 'خطأ في تحميل معلومات الشريك',
  'heartbeatSent': 'تم إرسال نبض القلب!',
  'failedToSendHeartbeat': 'فشل إرسال نبض القلب.',
  'messageSent': 'تم إرسال الرسالة!',
  'failedToSendMessage': 'فشل إرسال الرسالة.',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'theme': 'ثيم التطبيق',
  'changePartner': 'تغيير الشريك',
  'logout': 'تسجيل الخروج',
  'aboutApp': 'حول التطبيق',
  'languageUpdated': 'تم تحديث اللغة!',
  'themeColorSaved': 'تم حفظ إعدادات الثيم!',
  'confirmLogout': 'تأكيد تسجيل الخروج',
  'areYouSureLogout': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'yes': 'نعم',
  'cancel': 'إلغاء',
  'fillAllFields': 'يرجى ملء جميع الحقول بشكل صحيح.',
  'heartCodeExists': 'رمز القلب هذا موجود بالفعل. يرجى اختيار رمز آخر.',
  'nameAndGenderRequired': 'الرجاء إدخال اسمك واختيار جنسك.',
  'letter': 'حرف',
  'numbers': 'أرقام',
  'back': 'رجوع',
  'noPartnerToSend': 'لا يوجد شريك لإرسال نبض القلب إليه.',
  'noPartnerToSendMessage': 'لا يوجد شريك لإرسال رسالة إليه.',
  'messageCannotBeEmpty': 'لا يمكن أن تكون الرسالة فارغة.',
  'swipeToSend': 'اسحب لإرسال رسالة',
  'swipeMessage': 'مرحباً من HeartSync!',
  'menuButtonComingSoon': 'وظيفة زر القائمة قريباً!',
  'selectThemeColor': 'اختر لون الثيم:',
  'confirmChangePartner': 'تأكيد تغيير الشريك',
  'areYouSureChangePartner': 'هل أنت متأكد أنك تريد تغيير شريكك؟ هذا سيلغي الاقتران.',
  'partnerUnpaired': 'تم إلغاء اقتران الشريك بنجاح.',
  'copyright': '© 2024 HeartSync. جميع الحقوق محفوظة.',
  'appDescription': 'HeartSync هو تطبيق مصمم لمساعدتك على البقاء على اتصال مع من تحب من خلال التفاعلات والتذكيرات البسيطة.',
  'skipPairing': 'تخطي الربط',
  'confirmPairingTitle': 'تأكيد الاقتران',
  'confirmPairingMessage': 'هل تريد الاقتران مع {partnerName} ({partnerHeartCode})؟',
  'accept': 'قبول',
  'decline': 'رفض',
  'pairingRequestSent': 'تم إرسال طلب الاقتران. في انتظار تأكيد الشريك.',
  'pairingRequestReceived': 'تم استلام طلب الاقتران من {partnerName} ({partnerHeartCode}).',
  'pairingAccepted': 'تم الاقتران بنجاح! أنت متصل الآن.',
  'pairingDeclined': 'تم رفض الاقتران من قبل الشريك.',
  'pairingFailed': 'فشل الاقتران. يرجى المحاولة مرة أخرى.',
  'iMissYouSettingsTitle': 'إعدادات اشتقت إليك',
  'setReminderTime': 'تعيين وقت التذكير',
  'reminderTime': 'وقت التذكير',
  'enableReminders': 'تفعيل التذكيرات',
  'reminderMessage': 'حان الوقت لتفقد شريكك!',
  'reminderSaved': 'تم حفظ إعدادات التذكير!',
  'openAppSettings': 'فتح إعدادات التطبيق',
  'appSettingsExplanation': 'لضمان عمل التذكيرات، يرجى تفعيل الإشعارات لـ HeartSync في إعدادات جهازك.',
  'qrScannerTitle': 'مسح رمز QR',
  'scanQrCodeInstruction': 'ضع رمز QR داخل الإطار لمسحه.',
  'qrCodeNotFound': 'لم يتم العثور على رمز QR أو غير صالح.',
  'cameraPermissionDenied': 'تم رفض إذن الكاميرا. يرجى تمكينه في الإعدادات.',
  'home': 'الرئيسية',
  'iMissYouSettings': 'إعدادات اشتقت إليك',
  'welcome': 'مرحباً',
  'lastInteractionWith': 'آخر تفاعل مع',
  'noPartnerMessage': 'يبدو أنك لم تقترن بأحد بعد. توجه إلى شاشة الاقتران للاتصال بشريكك!',
  'goToPairing': 'انتقل للاقتران',
  'never': 'أبداً',
  'secondsAgo': 'ثانية مضت',
  'minutesAgo': 'دقيقة مضت',
  'hoursAgo': 'ساعة مضت',
  'daysAgo': 'يوم مضى',
  'noPartnerPaired': 'لم يتم الاقتران بشريك بعد.',
  'whatsYourName': 'ما اسمك؟',
  'yourNameHint': 'اسمك',
  'whatsYourHeartCode': 'ما هو رمز قلبك؟',
  'whatsYourGender': 'ما هو جنسك؟',
  'selectBirthdate': 'تاريخ ميلادك',
  'tapToPick': 'اضغط لاختيار التاريخ',
  'completeBasicInfo': 'الرجاء إدخال اسمك، اختيار جنسك، وإدخال رمز قلب صالح من 5 أحرف (مثال: A1234).',
  'birthdateRequired': 'الرجاء اختيار تاريخ ميلادك.',
  'settingsSaved': 'تم حفظ الإعدادات بنجاح!',
  'errorSavingSettings': 'خطأ في حفظ المعلومات. يرجى المحاولة مرة أخرى.',
  'myHeartCodeLabel': 'رمز قلبك:',
  'tapToCopy': 'اضغط للنسخ',
  'shareMyCode': 'مشاركة رمزي',
  'partnerHeartCodeLabel': 'رمز قلب الشريك:',
  'heartCodeRequired': 'الرجاء إدخال رمز قلب صالح من 5 أحرف (مثال: A1234)',
  'pairNow': 'اقترن الآن',
  'scanQRCode': 'مسح رمز QR',
  'cannotPairWithSelf': 'لا يمكنك الاقتران برمز قلبك الخاص.',
  'partnerCodeNotFound': 'لم يتم العثور على رمز قلب الشريك.',
  'partnerAlreadyPaired': 'هذا الشريك مقترن بالفعل بشخص آخر.',
  'pairingSuccess': 'تم الاقتران بنجاح!',
  'pairingError': 'فشل الاقتران',
  'copiedToClipboard': 'تم النسخ إلى الحافظة!',
  'invalidQrCode': 'تنسيق رمز QR غير صالح.',
  'skipPairingTitle': 'تخطي الاقتران',
  'skipPairingMessage': 'هل أنت متأكد أنك تريد تخطي الاقتران في الوقت الحالي؟ يمكنك الاقتران لاحقاً من الإعدادات.',
  'settingsTitle': 'الإعدادات',
  'themeColor': 'لون ثيم التطبيق',
  'logoutConfirmation': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'confirm': 'تأكيد',
  'themeUpdated': 'تم تحديث الثيم',
  'aboutAppTitle': 'حول',
};
